- hosts: awx
  become: yes
  user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install o Python'
      raw: 'yum install -y python'
    - name: 'Update o Repo'
      raw: 'yum -y update'
- hosts: awx
  become: yes
  user: root
  roles:
  - { role: install-awx, tags: ["install_awx"]}
    